name: loredart_tensor
description: A Dart-pure package for manipulation with tensors (multidimensional arrays of data) inspired by the TensorFlow API.
version: 1.0.1

homepage: https://github.com/suntez/loredart_tensor
repository: https://github.com/suntez/loredart_tensor

environment:
  sdk: '>=3.7.0 <4.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0